### ISSUE TITLE
一个小的需求

### ISSUE THREAD

**Issue by harttle** [tylerlong/slim_text#10]
你好！这个东西真是绝无仅有！
我在用本地的markdown做笔记，使用markdown previewer预览，使用这个插件进行编辑。
所以希望在chrome中打开本地文件后右键可以直接打开这个插件来编辑它。
因为很需要O(∩_∩)O，但看起来这个需求很小众。不知能不能有办法帮助我

**Comment by tylerlong** [comment]
不是很清楚需求: `在chrome中打开本地文件后右键可以直接打开这个插件来编辑它`

chrome直接打开本地文件? 然后在chrome里面再右键打开Slim Text?

如果能有截图的话会更容易理解你的需求.

**Comment by harttle** [comment]
嗯 是这样的。比如这样，我打开了这样的本地文件 希望这个右键菜单中有“使用Slim Text编辑”一项。不过这个菜单好像是当前插件控制的……其实即使是全局的菜单项我也很喜欢！
![image](https://f.cloud.github.com/assets/4427974/513316/7c7247fa-be3b-11e2-8d42-027cae68a7f1.png)

**Comment by harttle** [comment]
另外，在这个插件中输入中文时会产生额外的字符，暂时没有解决。以前类似的问题好像是关掉输入法的预编辑字符串什么的……不过之前是linux下，windows下还没有过这种问题

**Comment by tylerlong** [comment]
linux输入法的问题以前有过. 已经解决了. 我现在Ubuntu下面, ibus输入中文没有发现任何问题.

https://github.com/tylerlong/slimtext.org/issues/2

https://github.com/tylerlong/slimtext.org/issues/16

**Comment by tylerlong** [comment]
之前有一个人提过一个类似的需求. 就是在编辑markdown的时候, 按快捷键 ctrl + M 就能预览. 是不是这么实现更加合理些? 那样你就不需要markdown previewer了.

**Comment by harttle** [comment]
额 是这样的 
我本来希望有一个博客，支持本地文件同步、markdown
然而我在国内的教育网里~ 有几个好用的博客都不稳定，所以现在考虑静态建站，然后用网盘同步设备。
其实我需要一个工具可以方便的浏览、方便地编辑。一直没有找到较好的方案。
可能这样的需求和Slim Text有点偏离。

**Comment by tylerlong** [comment]
你说的输入中文的问题, 我昨天碰到了. 因为我本人一直在Linux下面使用, Windows没怎么关注. 昨天试了下在Windows下的中文输入竟然坏掉了! 可能是0.0.9版本引入的问题.

最新版已经修正了中文输入问题.

**Comment by tylerlong** [comment]
最新版的Slim Text支持Ctrl-M预览Markdown. 应该完全满足了`可以方便的浏览、方便地编辑`.
