### ISSUE TITLE
function needed for 4 spaces instead of Tab

### ISSUE THREAD

**Issue by shadu120** [tylerlong/slim_text#13]
Could you please add new function that support: replace tab content with customized spaces?

**Comment by tylerlong** [comment]
Ctrl-H

**Comment by shadu120** [comment]
看来我的英文确实很差，没有描述清楚。
我希望增加个一个功能，按下Tab键，插入4个空格。类似Notepad++里的tablesize replace with (4) space.
现在只能设置Tabl长度是4个字符，但不是空格。
用SlimText修改一些python历史代码文件很困难，需要手工敲4个空格才能做一次缩进呢。

**Comment by shadu120** [comment]
close的真快啊-_-

**Comment by tylerlong** [comment]
你真的确信现在插入的不是空格？

事实上， 只支持插入空格， 不支持插入tab
