### ISSUE TITLE
功能需求：“空格替代Tab字符”

### ISSUE THREAD

**Issue by shadu120** [tylerlong/slim_text#14]
看来我的英文确实很差，没有描述清楚。
我希望增加个一个功能，按下Tab键，插入4个空格。类似Notepad++里的tablesize replace with (4) space.
现在只能设置Tabl长度是4个字符，但不是空格。
用SlimText修改一些python历史代码文件很困难，需要手工敲4个空格才能做一次缩进呢。

话说，问题关闭得也太快了吧……

**Comment by tylerlong** [comment]
你描述的需求已经实现了。 插入的就是空格。 不是tab

**Comment by shadu120** [comment]
我从chrome Store安装的，按下Tab产生的不是空格啊，亲测。。。Win7+Chrome.

**Comment by tylerlong** [comment]
若真如你所说, 就诡异了. 我刚在在win7 64上测了, 是空格. 你何以确认是tab? 你要打开显示不可见字符的功能.

![image](https://f.cloud.github.com/assets/733544/528319/c0e0cfec-c124-11e2-91ba-647e5241535d.png)

![image](https://f.cloud.github.com/assets/733544/528323/e03789e4-c124-11e2-8234-bcbbf7acbf26.png)

![image](https://f.cloud.github.com/assets/733544/528326/0205cd74-c125-11e2-93ef-4bb2e7a2b12a.png)

**Comment by tylerlong** [comment]
我明白问题所在了。 Slim Text 有自动缩进检测功能。 如果python文件本身就有用tab做缩进， 那么slim text 也可能会用tab。 否则就一定会用空格。

你不妨先把文件里面的tab全部替换掉。 再试。（可能需要刷新下）
