### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by guiprav** [tylerlong/slim_text#18]
Maybe I'm just not looking at the right places, but I really couldn't find any indication of this software's license.

It doesn't matter if the software is open-source; if the license is not stated, it defaults to All Rights Reserved, which effectively means that the developers could sue anyone who redistributes the software (or parts of it), even if they're modified versions of the software. Or force them to stop redistribution.

Obviously this makes little sense in a platform like GitHub, so if this software is not already covered by a free license, please create a LICENSE file specifying one of your choice, and/or state it on the README file.

As usual, the best free software licenses are copyleft (e.g. GPL), so please consider those first. If GPL proves unfit for this project, consider LGPL. If for some crazy reason LGPL doesn't work, or if you think it's fair that your software be relicensed with a non-free license, and maybe incorporated into a proprietary product you have no control over, you can pick MIT / X11 or equivalents (there's lots of them). But please state a license.

Disregard all that if it's already covered by some free software license that I'm not aware of, and thanks for the awesome project.

**Comment by tylerlong** [comment]
Thank you for creating this issue. I didn't think about it before.

I Updated README file and chose [GPL](http://www.gnu.org/licenses/gpl.html) as the Software license.
