### ISSUE TITLE
开发者教程

### ISSUE THREAD

**Issue by tylerlong** [tylerlong/slim_text#3]
# 开发者教程
## 安装软件

[CoffeeScript](http://coffeescript.org/)
## 快速开始

```
git clone git@github.com:tylerlong/slim_text.git
cd slim_text
git submodule update --init --recursive
coffee --watch --output js/ --compile coffee/
```

**备注**: 建议先fork一个自己的Repo, 再`git clone`
## 测试
1. 浏览器打开`chrome://extensions/`
2. 勾选`开发者模式`
3. 选择 `载入未打包的扩展`
4. 浏览到slim_text项目的根文件夹, 确定载入
5. 即可在浏览器中测试开发版的Slim Text了

![image](https://f.cloud.github.com/assets/733544/492647/fd353bbe-bacf-11e2-8b0b-f68103807966.png)
## 贡献代码
1. 先fork一个自己的Repo
2. 将自己的Repo `git clone` 到本地
3. 修改代码, commit, push
4. 创建Pull Request
5. 修改的代码被review, 合并到官方代码库

**Comment by hugohua** [comment]
有没有提供相应的接口？
比如我网页有段代码要编辑，直接跳转到插件页面编辑完后再把数据传回来？

**Comment by tylerlong** [comment]
@baofen14787 没有这样的接口。

**Comment by zjyExcelsior** [comment]
macOS Sierra下，打开Slim Text只显示两条黑线
