### ISSUE TITLE
有没有配置选项可以不让显示.开始的文件或目录

### ISSUE THREAD

**Issue by williamherry** [tylerlong/slim_text#6]
我用Linux家目录下会有好多隐藏文件和目录

**Comment by tylerlong** [comment]
暂时没有. 这个问题有人提过. 有一些文件还是有用的, 比如 `.gitignore`文件, 经常需要编辑.

我考虑下一个版本加一个配置项, 可以让用户选择隐藏这些文件

**Comment by williamherry** [comment]
刚看了一下好像也没必要了,因为会记录上次编辑的位置和文件,这个问题只有在第一次打开的时候会有
