### ISSUE TITLE
show/hide invisibles under linux 3.8.11 doesn't work

### ISSUE THREAD

**Issue by bighzl** [tylerlong/slim_text#8]
look up to the title...

**Comment by bighzl** [comment]
chrome extensions,0.0.9

**Comment by bighzl** [comment]
under vim mode, : mode doesn't work

**Comment by tylerlong** [comment]
> show/hide invisibles under linux 3.8.11 doesn't work

![image](https://f.cloud.github.com/assets/733544/496989/37883a8e-bbf0-11e2-9718-dbd4acc1ba06.png)

> under vim mode, : mode doesn't work

It is a known issue and won't be fixed. Slim Text is NOT 100% compatible with Vim.
