### ISSUE TITLE
是否能增加 支持插件 还有 代码片段

### ISSUE THREAD

**Issue by septs** [tylerlong/slim_text#9]
RT

**Comment by tylerlong** [comment]
Slim Text 底层基于ACE. ACE是有插件机制的. 可能在它的基础上再开发一下.

代码片段这个功能我很少见过. 比如什么编辑器或者IDE提供了类似的功能?

**Comment by cailiang9** [comment]
他应该是想像vs c++一样，输入for、if的时候补全大括号。

**Comment by suuuch** [comment]
代码片段这个功能，是不是在PHPstorm 里面ctrl+j出来的那个代码片段。ctrl+j 是调出代码片段的缩写，选中则会出现你已经添加在代码片段中的某一段代码。
比如ctrl +j ，然后选中fore 就会出现完整的foreach循环代码：
foreach($array as $key=>$values)
{
//other code.....
}  个人觉得这个才是代码片段。也觉得这个功能很实用。

**Comment by tylerlong** [comment]
可以考虑让用户预定义一些代码片段, 然后快捷键选择插入当前编辑器. 这个主意不错.

我打算给Slim Text设计一个通用的插件机制. 所有的这些特殊功能(代码片段, markdown preview等等), 都采用插件的方式来实现. 不至于把核心代码弄得太庞大.

**Comment by suuuch** [comment]
额。对。说说我个人意见好吧。有不对的地方。直接无视把。我觉得这个slim 就是一个轻量级的编辑器，可以借鉴sublime 跟VIM或者emac这种编辑器的插件模式。维护主要功能的轻便易用，允许第三方插件开发。这个是最节省时间跟精力的。

**Comment by cailiang9** [comment]
都开源的，搞插件机制没有必要，实际上支持常用的语言snippet（c++ tex js）就行了，剩下的由别人开发好可以再merge
